### ISSUE TITLE
Unable to run on fresh new install

### ISSUE THREAD

**Issue by Enelar** [jenssegers/php-proxy#40]
`PHP Fatal error:  Class 'Zend\\Diactoros\\ServerRequestFactory' not found in /var/www/html/index.php on line 10`

**Comment by hervethouzard** [comment]
In your composer.json add this line:
"zendframework/zend-diactoros": "^1.3"

**Comment by Enelar** [comment]
@hervethouzard isnt `"zendframework/zend-diactoros": "^1.0"` similar?

**Comment by kfriend** [comment]
@Enelar I ran into this issue as well. I believe it's because the example in the readme is for the latest version of the package, i.e. the 3 beta version. But, when you install with `composer require jenssegers/proxy`, it will install that latest stable for the 2.2 series. If you install with `composer require jenssegers/proxy v3.0.0-beta2`, the readme example will match the installed version.

**Comment by tejastank** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1

 - The requested package jenssegers/proxy No version set (parsed as 1.0.0) is satisfiable by 

jenssegers/proxy[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for jenssegers/proxy v3.0.0-beta2 -> satisfiable by jenssegers/proxy[v3.0.0-beta2].
    - jenssegers/proxy v3.0.0-beta2 requires relay/relay ^0.2.0 -> satisfiable by relay/relay[0.2.0] but these conflict with your requirements or minimum-stability.

**Comment by jcamejo** [comment]
@tejastank Remove the package and reinstall it as suggested by @kfriend

**Comment by tejastank** [comment]
@jcamejo thanks mate, I will keep your suggestion and will try to do.

**Comment by jenssegers** [comment]
Make sure you try the new 3.0.0 version, which is not beta anymore.
